### ISSUE TITLE
Feature: Close RFC as failed

### ISSUE THREAD

**Issue by eric-nord** [byu-oit/standard-change-lambda#1]
Record failure start and failure end times

Here are the valid close statuses from it.byu.edu and their code:
1 Excellent
2 Excellent with Down Time
3 Fair
4 Poor
5 Unsuccessful

**Comment by TravisAGengler** [comment]
I propose we add an optional parameter to our lambda invocation event called 'status' for manual control at invocation. This makes most sense for use outside of CodePipeline

For determining success or failure of a CodePipeline action that a standard change hinges on, I suggest we create a parallel action to the critical action that monitors the status of its stack using AWS API calls and closes the ticket accordingly. For this to work, our lambda would need to have the pipeline name it is currently part of. This could easily be passed as a User parameter to the lambda. User parameters can be defined manually through the aws console or as a configuration item in a cloudformation template for a CodePipeline lambda invoke action.

What are your thoughts? Can you think of any other use cases?

**Comment by TravisAGengler** [comment]
This is now possible by adding a "status" field to invocations of this lambda as outlined in the README. Tickets for failed pipelines are currently closed by the open_change_cleanup lambda. We will likely iterate on this design in the future
